apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  generation: 1
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.14.2
    chart: kube-prometheus-stack-80.14.2
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  externalUrl: "http://monitoring-kube-prometheus-alertmanager.monitoring:9093"
  image: quay.io/prometheus/alertmanager:v0.30.1
  imagePullPolicy: IfNotPresent
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: monitoring-kube-prometheus-alertmanager
  version: v0.30.1
  # Reference the secret with the alertmanager config using alertmanagerConfigNamespaceSelector
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanager: monitoring-kube-prometheus-alertmanager  # Match the label
  volumes:
    - name: alertmanager-config
      secret:
        secretName: alertmanager-config  # Use the Secret that you created with alertmanager.yaml
  volumeMounts:
    - name: alertmanager-config
      mountPath: /etc/alertmanager/alertmanager.yaml
      subPath: alertmanager.yaml
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2026-01-19T14:17:27Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-16T16:51:42Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Reconciled
  paused: false
  replicas: 1
  selector: alertmanager=monitoring-kube-prometheus-alertmanager,app.kubernetes.io/instance=monitoring-kube-prometheus-alertmanager,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager
  unavailableReplicas: 0
  updatedReplicas: 1
