apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-creds
  namespace: monitoring
type: Opaque
stringData:
  SMTP_USERNAME: YWJoaWxhc2hrb25kYTc3MEBnbWFpbC5jb20=
  SMTP_PASSWORD: bmJkc2tkYnJjdGRqemhudw==
