apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sechay-website
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sechay-website
  template:
    metadata: 
      labels: 
        app: sechay-website
    spec: 
      containers: 
        - name: sechay-website
          image: IMAGE_PLACEHOLDER
          ports: 
            - containerPort: 80

