apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sechay-website-blue
  namespace: enterprise-website
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sechay-website
      version: blue
  template:
    metadata: 
      labels: 
        app: sechay-website
        version: blue
    spec: 
      containers: 
        - name: sechay-website
          image: abhilash369/enterprise-website:26
          ports: 
            - containerPort: 80
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - -nginx.scrape-uri=http://127.0.0.1/nginx_status
          ports:
            - containerPort: 9113
