apiVersion: v1
kind: Service
metadata:
  name: sechay-website-service
  namespace: enterprise-website
  labels:
    app: sechay-website
spec:
  type: NodePort
  selector:
    app: sechay-website
    version: blue
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30076
  - name: metrics
    port: 9113
    targetPort: 9113
